version: '3'
services:
  teams-bot-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        npm run build
        npm run dev
    ports:
      - '3978:3978'
    tty: true
