version: '3'
services:
  teams-bot-app:
    image: node:18.16
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        npm run build
        npm run dev
    ports:
      - '3978:3978'
    tty: true
